version: "3.8"

services:
  caddy:
    image: caddy:alpine
    container_name: main-proxy
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - playlab

  playlab:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: playlab
    ports:
      - "8083:3000"
